### ISSUE TITLE
Write Hellp world in C++

### ISSUE THREAD

**Issue by Mozilla-Campus-Club-CCOEW** [Mozilla-Campus-Club-CCOEW/FirstPullRequest#1]
- [x] C

- [ ] Java

- [ ] C++

-

**Comment by Shr03mink** [comment]
please assign me this issue in c @Mozilla-Campus-Club-CCOEW as a part of xyz program

**Comment by Mozilla-Campus-Club-CCOEW** [comment]
Please review PR #2

**Comment by Shr03mink** [comment]
Please review PR #2

**Comment by Mozilla-Campus-Club-CCOEW** [comment]
Merges PR #2

**Comment by Shr03mink** [comment]
assign this to me in c++
